mongo:
  image: mongo
  volumes:
    - ./data:/data/db
  ports:
    - 27017:27017
  environment:
    - storageEngine:wiredTiger  

mongo-express:
  image: mongo-express
  links:
    - mongo:mongo
  ports:
    - 8081:8081

